spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: none # 테이블 생성 옵션
    properties:
      hibernate:
        show_sql: true
        format_sql: true # hibernate 쿼리 포맷 pretty
        default_batch_fetch_size: 100
    open-in-view: false
  data:
    web:
      pageable:
        default-page-size: 10
server:
  error:
    whitelabel:
      enabled: false
  forward-headers-strategy: native