spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&allowPublicKeyRetrieval=true
    username: testdb
    password: pass

  jpa:
    hibernate:
      ddl-auto: create # 테이블 생성 옵션
    properties:
      hibernate:
        format_sql: true # hibernate 쿼리 포맷 pretty
        default_batch_fetch_size: 100
    open-in-view: false

  data:
    web:
      pageable:
        default-page-size: 10

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace # 쿼리 파라미터 로깅